/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package capaVistas;

import capalogica.DepartamentosDAO;
import capalogica.EmpleadosDAO;
import capalogica.TodosLogica;
import capalogica.todoDAO;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
import java.util.Date;
import java.text.DateFormat;  
import java.time.LocalDate;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author alexd
 */
public class AgregarTodo extends javax.swing.JInternalFrame {

    /**
     * Creates new form AgregarTodo
     */
    
    DefaultTableModel dibujo;
    int IndexEmpleado=0;
    boolean EstaEditando = false;
    public AgregarTodo() {
        initComponents();
        dibujo = new DefaultTableModel();
        dibujo.addColumn("ID");
        dibujo.addColumn("Empleado");
        dibujo.addColumn("Departamento");
        dibujo.addColumn("Tarea");
        dibujo.addColumn("Fecha Inicio");
        dibujo.addColumn("Fecha Fin");
        dibujo.addColumn("Prioridad");
        
        jTable1.setModel(dibujo);
        llenarComboEmpleado();
        llenarComboDepa();
        llenarListado();
        LLenarprioridades();
        
        
    }

    
    void llenarComboEmpleado(){
        TodosLogica tdo = new TodosLogica();
        ArrayList<EmpleadosDAO> lstEmpleado = tdo.getEmpleados();
        
        for(EmpleadosDAO EMPDAORegistro : lstEmpleado){
            
            
            
            cmbEmpleados.addItem(EMPDAORegistro.getNombres()+" "+ EMPDAORegistro.getApellidos());
        }
    }
    
    void llenarComboDepa(){
        TodosLogica tdo = new TodosLogica();
        ArrayList<DepartamentosDAO> lstDepa = tdo.getDepartamentos();
        
        for(DepartamentosDAO EMPDAORegistro : lstDepa){
            
            
            
            cmbDepartamento.addItem(EMPDAORegistro.getNombre());
        }
    }
    
    void LLenarprioridades(){
        TodosLogica tdo = new TodosLogica();
        String PrioridadesBajas = tdo.PrioridadesBajas();
        lblBajas.setText(PrioridadesBajas);
        
        String PrioridadesInter = tdo.PrioridadIntermedia();
        lblInte.setText(PrioridadesInter);
        
        String PrioridadAlta = tdo.PrioridadAlta();
        lblPrioAlt.setText(PrioridadAlta);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtTarea = new javax.swing.JTextArea();
        dtInicio = new com.toedter.calendar.JDateChooser();
        dtFin = new com.toedter.calendar.JDateChooser();
        cmbPrioridad = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        cmbEmpleados = new javax.swing.JComboBox<>();
        cmbDepartamento = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblPrioAlt = new javax.swing.JLabel();
        lblBajas = new javax.swing.JLabel();
        lblInte = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setOpaque(true);

        jLabel1.setBackground(new java.awt.Color(51, 153, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tareas por hacer.");
        jLabel1.setOpaque(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Datos de Ingreso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Prioridad");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Tarea:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Fecha Inicio:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Fecha Fin:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Empleado:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Departamento");

        txtTarea.setColumns(20);
        txtTarea.setRows(5);
        txtTarea.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTareaKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtTarea);

        dtInicio.setDateFormatString("yyyy-MM-dd");
        dtInicio.setMinSelectableDate(new java.util.Date(-62135744291000L));

        dtFin.setDateFormatString("yyyy-MM-dd");

        cmbPrioridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "Bajo", "Intermedio", "Alto", " " }));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Nueva Tarea");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        cmbEmpleados.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione..." }));

        cmbDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione..." }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnGuardar)
                        .addGap(14, 14, 14)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpiar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(dtInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cmbDepartamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(10, 10, 10)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cmbPrioridad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(dtFin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbEmpleados, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap(20, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dtInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(dtFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnEliminar)
                    .addComponent(btnLimpiar))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.ABOVE_TOP));

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setGridColor(new java.awt.Color(51, 153, 255));
        jTable1.setRowHeight(32);
        jTable1.setSelectionBackground(new java.awt.Color(51, 153, 255));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Tareas Bajas");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel10.setText("Tareas Intermedias");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel11.setText("Tareas Altas");

        lblPrioAlt.setBackground(new java.awt.Color(255, 0, 0));
        lblPrioAlt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPrioAlt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrioAlt.setText("0");
        lblPrioAlt.setOpaque(true);

        lblBajas.setBackground(new java.awt.Color(255, 255, 51));
        lblBajas.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblBajas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBajas.setText("0");
        lblBajas.setOpaque(true);

        lblInte.setBackground(new java.awt.Color(102, 255, 102));
        lblInte.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblInte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInte.setText("0");
        lblInte.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBajas, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(lblInte, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrioAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(140, 140, 140))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrioAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblBajas, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblInte, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        if (EstaEditando == false) {
            TodosLogica tdo = new TodosLogica();
            todoDAO todoDAO = new todoDAO();
            Date dt = new Date();
            int cmb = cmbEmpleados.getSelectedIndex();
            int dep = cmbDepartamento.getSelectedIndex();
            String tarea = txtTarea.getText();
            Date dtInit = dtInicio.getDate();
            Date dtFinal = dtFin.getDate();
            int prioridad = cmbPrioridad.getSelectedIndex();

            //Formateando fechas
            try {
                DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");  
                String strDate = dateFormat.format(dtInit);
                String strDateFin = dateFormat.format(dtFinal);

                todoDAO.setEmpleado(cmb);
                todoDAO.setDepartamento(dep);
                todoDAO.setFecha_inicio(strDate);
                todoDAO.setFecha_fin(strDateFin);
                todoDAO.setPrioridad(prioridad);
                todoDAO.setTarea(tarea);

                tdo.LLenarData(todoDAO);
                llenarListado();
                Limpiar();
                LLenarprioridades();
            }catch(Exception e){System.out.println("Error de parseo");}
        }else {
            TodosLogica tdo = new TodosLogica();
            todoDAO todoDAO = new todoDAO();
            Date dt = new Date();
            int index = jTable1.getSelectedRow();
            int id = (int)jTable1.getValueAt(index, 0);
            int cmb = cmbEmpleados.getSelectedIndex();
            int dep = cmbDepartamento.getSelectedIndex();
            String tarea = txtTarea.getText();
            Date dtInit = dtInicio.getDate();
            Date dtFinal = dtFin.getDate();
            int prioridad = cmbPrioridad.getSelectedIndex();

            //Formateando fechas
            try {
                DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");  
                String strDate = dateFormat.format(dtInit);
                String strDateFin = dateFormat.format(dtFinal);
                todoDAO.setId(id);
                todoDAO.setEmpleado(cmb);
                todoDAO.setDepartamento(dep);
                todoDAO.setFecha_inicio(strDate);
                todoDAO.setFecha_fin(strDateFin);
                todoDAO.setPrioridad(prioridad);
                todoDAO.setTarea(tarea);

                tdo.PrepararDataEdit(todoDAO);
                llenarListado();
                Limpiar();
                LLenarprioridades();
                JOptionPane.showMessageDialog(null, "Tarea  Editada");
            }catch(Exception e){System.out.println("Error de parseo");}
        
        }
        
        
        
        
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        

        try {
            int index = jTable1.getSelectedRow();
        
            cmbEmpleados.setSelectedItem(jTable1.getValueAt(index, 1).toString());
            cmbDepartamento.setSelectedIndex((int)jTable1.getValueAt(index, 7));
            txtTarea.setText(jTable1.getValueAt(index, 3).toString());
            String fecha = jTable1.getValueAt(index, 4).toString();
            String fechaFin = jTable1.getValueAt(index, 5).toString();
            SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH);
            Date lc = formatter.parse(fecha);
            Date ff = formatter.parse(fechaFin);
            dtInicio.setDate(lc);
            dtFin.setDate(ff);
            IndexEmpleado = (int)jTable1.getValueAt(index, 0);
            EstaEditando =true;
            btnGuardar.setText("Actualizar");
        }catch(Exception e){}
        
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        Limpiar();
        
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        TodosLogica tdo = new TodosLogica();
        JOptionPane.showMessageDialog(null, tdo.EliminarToDo(IndexEmpleado));
        llenarListado();
        Limpiar();
        LLenarprioridades();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtTareaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTareaKeyTyped
        // TODO add your handling code here:
        txtTarea.setLineWrap(true);
    }//GEN-LAST:event_txtTareaKeyTyped

    void Limpiar(){
        cmbEmpleados.setSelectedIndex(0);
        cmbDepartamento.setSelectedIndex(0);
        txtTarea.setText("");
        dtInicio.setCalendar(null);
        dtFin.setCalendar(null);
        cmbPrioridad.setSelectedIndex(0);
        EstaEditando = false;
        btnGuardar.setText("Guardar");
    }
    
    public void llenarListado(){

        dibujo = new DefaultTableModel();
        dibujo.addColumn("ID");
        dibujo.addColumn("Empleado");
        dibujo.addColumn("Departamento");
        dibujo.addColumn("Tarea");
        dibujo.addColumn("Fecha Inicio");
        dibujo.addColumn("Fecha Fin");
        dibujo.addColumn("Prioridad");
        dibujo.addColumn("Index");

        jTable1.setModel(dibujo);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        
        jTable1.getTableHeader().getColumnModel().getColumn(0).setMaxWidth(0);
        jTable1.getTableHeader().getColumnModel().getColumn(0).setMinWidth(0);
        
        
        jTable1.getColumnModel().getColumn(7).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(7).setMinWidth(0);
        
        jTable1.getTableHeader().getColumnModel().getColumn(7).setMaxWidth(0);
        jTable1.getTableHeader().getColumnModel().getColumn(7).setMinWidth(0);
        TodosLogica tdo = new TodosLogica();
        ArrayList<todoDAO> lstUsuarios = tdo.getTodoList();
        
        for(todoDAO todo : lstUsuarios){
            
            Vector registro = new Vector();
            
            registro.add(todo.getId());
            registro.add(todo.getNombres()+" "+todo.getApellidos());
            registro.add(todo.getNombre_departamento());
            registro.add(todo.getTarea());
            registro.add(todo.getFecha_inicio());
            registro.add(todo.getFecha_fin());
            String Prioridad = ValidarPrioridad(todo.getPrioridad());
            registro.add(Prioridad);
            registro.add(todo.getDepartamento());
            dibujo.addRow(registro);
        }
                

        
    }
    
    String ValidarPrioridad(int prio){
        String Prioridad ="";
        if (prio == 1) {
            Prioridad = "Baja";
        }else if (prio ==2) {
            Prioridad = "Intermedia";
        }else if (rootPaneCheckingEnabled) {
            Prioridad = "Alta";
        }
   
        return Prioridad;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cmbDepartamento;
    private javax.swing.JComboBox<String> cmbEmpleados;
    private javax.swing.JComboBox<String> cmbPrioridad;
    private com.toedter.calendar.JDateChooser dtFin;
    private com.toedter.calendar.JDateChooser dtInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBajas;
    private javax.swing.JLabel lblInte;
    private javax.swing.JLabel lblPrioAlt;
    private javax.swing.JTextArea txtTarea;
    // End of variables declaration//GEN-END:variables
}
